#!/bin/bash
function _seal()
{
    local filesize=$((RANDOM % 17 + 1))m
    $GEN_RANDOM_DATA ${filesize} $datadir/$filesize
    if [ $? -ne 0 ]; then
        verbose ERROR "generate random data failed!"
        exit 1
    fi
    local cid_l=$(seal $datadir/$filesize)
    rm $datadir/$filesize
    if [ ${#cid_l} -ne 46 ]; then
        verbose ERROR "seal file failed!"
        exit 1
    fi
    echo $cid_l
}

function _store_meta()
{
    validate_file
    store_metadata
}

function seal_exit()
{
    rm -rf $tmpdir
}

########## MAIN BODY ##########
# basic variable
basedir=$(cd `dirname $0`;pwd)
instdir=$(cd $basedir/..;pwd)
scriptdir=$instdir/scripts
datadir=$instdir/data
testdir=$instdir/test_app
testfiledir=$testdir/files
tmpdir=$basedir/tmp
TMPFILE=$tmpdir/TMPFILE.$(date +%N)${RANDOM}

mkdir -p $tmpdir

trap 'seal_exit' EXIT

. $scriptdir/utils.sh


declare -A cid_2_use_m
data_arry=($(ls $datadir))
data_size=${#data_arry[@]}
acc=6

# Seal some file
while [ $acc -gt 0 ]; do
    # Randomly seal file
    index=$(($RANDOM % $data_size))
    _seal &>$TMPFILE
    cid=$(cat $TMPFILE 2>/dev/null)
    if [ x"$cid" != x"" ] && [ ${#cid} -ge 46 ]; then
        cid=${cid:0:46}
        cid_2_use_m[$cid]=0
    else
        verbose ERROR "Cannot get wrong sealed cid($cid)!" n
        exit 1
    fi
    ((acc--))
done

# Delete valid file sequently
acc=2
for cid in ${!cid_2_use_m[@]}; do
    delete_file $cid &>/dev/null
    if [ $? -ne 0 ]; then
        verbose ERROR "delete file sequently failed!" n
        exit 1
    fi
    cid_2_use_m[$cid]=1
    if get_file_info_all | grep "$cid" &>/dev/null; then
        verbose ERROR "delete file:$cid failed!Find cid in workload" n
        exit 1
    fi
    if [ $((acc--)) -le 0 ]; then
        break
    fi
done

# Delete confirmed file concurrently
delete_arry=()
acc=0
for cid in ${!cid_2_use_m[@]}; do
    if [ ${cid_2_use_m[$cid]} -eq 0 ]; then
        delete_file $cid &>/dev/null &
        delete_arry[$acc]=$cid
        ((acc++))
    fi
done
sleep 10
for cid in ${delete_arry[@]}; do
    if get_file_info_all | grep "$cid" &>/dev/null; then
        verbose ERROR "delete file concurrently failed!" n
        exit 1
    fi
done
