#define CRUST_INST_DIR      "/opt/crust"
#define ENCLAVE_FILE_PATH   CRUST_INST_DIR "/etc/enclave.signed.so"
#define IPC_FILE_PATH       CRUST_INST_DIR "/.ipc"
#define LOG_FILE_PATH       CRUST_INST_DIR "/log/crust.log"
#define CONFIG_FILE_PATH    CRUST_INST_DIR "/etc/Config.json"
