#define CRUST_INST_DIR      "/opt/crust/crust-tee"
#define ENCLAVE_FILE_PATH   CRUST_INST_DIR "/etc/enclave.signed.so"
#define IPC_FILE_PATH       CRUST_INST_DIR "/.ipc"
#define WL_FILE_PATH        CRUST_INST_DIR "/.wl_ipc"
#define KP_FILE_PATH        CRUST_INST_DIR "/.kp_ipc"
#define MW_FILE_PATH        CRUST_INST_DIR "/.mw_ipc"
#define LOG_FILE_PATH       CRUST_INST_DIR "/log/crust.log"
#define CONFIG_FILE_PATH    CRUST_INST_DIR "/etc/Config.json"
#define WORK_REPORT_PATH    CRUST_INST_DIR "/etc/work_report.data"

#define APP_RUN_MODE_SINGLE "single"
#define APP_RUN_MODE_MULTIPLE "multiple"
